/* eslint-disable */

export function getOptionBoxColumns() {
  return [
    {
      desc: 'This shows the date and time of the transaction.',
      extraClass: '',
      identifier: 'dasher',
      isSelected: true,
      isHidden: false,
      name: 'Transaction Date',
      readOnly: true,
      required: true,
      isRequired: true,
    },
    {
      desc: 'This shows the transaction amount in the selected currency',
      extraClass: '',
      identifier: 'toto',
      isSelected: true,
      isHidden: false,
      name: 'Transaction Amount',
    },
    {
      desc: 'This shows the card account number that was used for the transaction.',
      extraClass: '',
      identifier: 'prancer',
      isSelected: false,
      isHidden: true,
      name: 'Card Number',
    },
    {
      desc: 'This shows the issuer of the card used in the transaction.',
      extraClass: '',
      identifier: 'vixen',
      isSelected: false,
      isHidden: false,
      name: 'Card Type',
    },
    {
      desc: 'Batches Merchant Number.',
      extraClass: '',
      identifier: 'alpha',
      isSelected: false,
      isHidden: false,
      name: 'Merchant Number',
    },
    {
      desc: 'Batches Private Label Purchase Count.',
      extraClass: '',
      identifier: 'beta',
      isSelected: false,
      isHidden: false,
      name: 'Private Label Purchase Count',
    },
    {
      desc: 'Batches Corp.',
      extraClass: '',
      identifier: 'zeta',
      isSelected: false,
      isHidden: false,
      name: 'Corp',
    },
    {
      desc: 'Batches Batch Count',
      extraClass: '',
      identifier: 'one',
      isSelected: false,
      isHidden: false,
      name: 'Batch Count',
    },
    {
      desc: 'Batches Discover Purchase Amount',
      extraClass: '',
      identifier: 'two',
      isSelected: false,
      isHidden: false,
      name: 'Discovery Purchase Amount',
    },
    {
      desc: 'Batches Discover Refund Count',
      extraClass: '',
      identifier: 'three',
      isSelected: false,
      isHidden: false,
      name: 'Discover Refund Count',
    },
    {
      desc: 'Batches Private Label Purchase Count',
      extraClass: '',
      identifier: 'four',
      isSelected: false,
      isHidden: false,
      name: 'Private Label Purchase Count',
    },
    {
      desc: 'Batches MasterCard Purchase Amount',
      extraClass: '',
      identifier: 'five',
      isSelected: false,
      isHidden: false,
      name: 'MasterCard Purchase Amount',
    },
    {
      desc: 'Batches MasterCard Refund Count',
      extraClass: '',
      identifier: 'six',
      isSelected: false,
      isHidden: false,
      name: 'MasterCard Refund Count',
    },
  ]
}

export function getCustomReportColumns() {
  return [
    {
      templateColumnId: 123,
      displayOrder: 0,
      visible: true
    },
    {
      templateColumnId: 334,
      displayOrder: 1,
      visible: false
    },
    {
      templateColumnId: 64,
      displayOrder: 2,
      visible: true
    },
    {
      templateColumnId: 65,
      displayOrder: 3,
      visible: true
    },
    {
      templateColumnId: 67,
      displayOrder: 4,
      visible: true
    },
    {
      templateColumnId: 68,
      displayOrder: 5,
      visible: true
    },
    {
      templateColumnId: 69,
      displayOrder: 6,
      visible: true
    },
    {
      templateColumnId: 999,
      displayOrder: 7,
      visible: true
    }
  ]
}

export function getTemplateColumns() {
  return [
    {
      defaultIsVisible: true,
      description: 'Batches Corp',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Corp',
      reportColumnId: 123,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 123,
      displayType: 'STRING',
      columnKey: 'corp',
      categoryDescription: 'Transaction Finder MID Hierarchy',
      categoryKey: 'header',
      categoryName: 'MID Hierarchy',
      displayOrder: 90,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Principal',
      isRequired: true,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Principal',
      reportColumnId: 125,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 125,
      displayType: 'STRING',
      columnKey: 'principal',
      categoryDescription: 'Transaction Finder MID Hierarchy',
      categoryKey: 'header',
      categoryName: 'MID Hierarchy',
      displayOrder: 92,
      isHidden: true,
    },
    {
      defaultIsVisible: true,
      description: 'Batches ETL Batch ID',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'ETL Batch ID',
      reportColumnId: 133,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 133,
      displayType: 'STRING',
      columnKey: 'etlbatchid',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 100,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Discover Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Discover Purchase Amount',
      reportColumnId: 84,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 84,
      displayType: 'CURRENCY',
      columnKey: 'di_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 51,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Private Label Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Private Label Purchase Count',
      reportColumnId: 109,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 109,
      displayType: 'STRING',
      columnKey: 'pl_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 76,
    },
    {
      defaultIsVisible: true,
      description: 'Batches MasterCard Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'MasterCard Refund Count',
      reportColumnId: 105,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 105,
      displayType: 'STRING',
      columnKey: 'mc_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 72,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Batch Count',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Batch Count',
      reportColumnId: 38,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 38,
      displayType: 'STRING',
      columnKey: 'batch_count',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 5,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Discover Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Discover Refund Count',
      reportColumnId: 87,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 87,
      displayType: 'STRING',
      columnKey: 'di_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 54,
    },
    {
      defaultIsVisible: true,
      description: 'Batches JCB Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'JCB Purchase Count',
      reportColumnId: 97,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 97,
      displayType: 'STRING',
      columnKey: 'jcb_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 64,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Refund Count',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Refund Count',
      reportColumnId: 44,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 44,
      displayType: 'STRING',
      columnKey: 'refund_count',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 11,
    },
    {
      defaultIsVisible: false,
      description: 'Batches China Union Pay Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'China Union Pay Refund Amount',
      reportColumnId: 68,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 68,
      displayType: 'CURRENCY',
      columnKey: 'cup_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 35,
    },
    {
      defaultIsVisible: true,
      description: 'Batches CBRT Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'CBRT Refund Amount',
      reportColumnId: 62,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 62,
      displayType: 'CURRENCY',
      columnKey: 'cbrt_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 29,
    },
    {
      defaultIsVisible: false,
      description: 'Sequence Key Description',
      isRequired: true,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Sequence Key',
      reportColumnId: 307,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 334,
      displayType: 'STRING',
      columnKey: 'seq_key',
      categoryDescription: 'Settled Transactions Batch Control Number',
      categoryKey: 'authorizationInformation',
      categoryName: 'Visa Product ID',
      displayOrder: 0,
      isHidden: true,
    },
    {
      defaultIsVisible: true,
      description: 'Batches EBT Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'EBT Purchase Count',
      reportColumnId: 91,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 91,
      displayType: 'STRING',
      columnKey: 'ebt_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 58,
    },
    {
      defaultIsVisible: true,
      description: 'Batches EBT Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'EBT Refund Count',
      reportColumnId: 93,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 93,
      displayType: 'STRING',
      columnKey: 'ebt_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 60,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Adjustment Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Adjusted Purchase Amount',
      reportColumnId: 48,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 48,
      displayType: 'CURRENCY',
      columnKey: 'adj_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 15,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Diners Club Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Diners Club Refund Count',
      reportColumnId: 81,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 81,
      displayType: 'STRING',
      columnKey: 'dc_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 48,
    },
    {
      defaultIsVisible: true,
      description: 'Batches MasterCard Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'MasterCard Count',
      reportColumnId: 101,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 101,
      displayType: 'STRING',
      columnKey: 'mc_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 68,
    },
    {
      defaultIsVisible: true,
      description: 'Batches China Union Pay Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'China Union Pay Refund Count',
      reportColumnId: 69,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 69,
      displayType: 'STRING',
      columnKey: 'cup_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 36,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Hierarchy',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Hierarchy',
      reportColumnId: 131,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 131,
      displayType: 'STRING',
      columnKey: 'hierarchy',
      categoryDescription: 'Transaction Finder MID Hierarchy',
      categoryKey: 'header',
      categoryName: 'MID Hierarchy',
      displayOrder: 98,
    },
    {
      defaultIsVisible: true,
      description: 'Batches EBT Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'EBT Purchase Amount',
      reportColumnId: 90,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 90,
      displayType: 'CURRENCY',
      columnKey: 'ebt_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 57,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Return Credit Amount',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Return Credit Amount',
      reportColumnId: 121,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 121,
      displayType: 'CURRENCY',
      columnKey: 'return_credit_amount',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 88,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Private Label Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Private Label Refund Amount',
      reportColumnId: 110,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 110,
      displayType: 'CURRENCY',
      columnKey: 'pl_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 77,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Private Label Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Private Label Refund Count',
      reportColumnId: 111,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 111,
      displayType: 'STRING',
      columnKey: 'pl_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 78,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Amex Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Amex Refund Amount',
      reportColumnId: 56,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 56,
      displayType: 'CURRENCY',
      columnKey: 'ax_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 23,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Amex Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Amex Count',
      reportColumnId: 53,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 53,
      displayType: 'STRING',
      columnKey: 'ax_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 20,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Private Label Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Private Label Purchase Amount',
      reportColumnId: 108,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 108,
      displayType: 'CURRENCY',
      columnKey: 'pl_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 75,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Discover Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Discover Refund Amount',
      reportColumnId: 86,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 86,
      displayType: 'CURRENCY',
      columnKey: 'di_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 53,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Discover Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Discover Batch Amount',
      reportColumnId: 82,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 82,
      displayType: 'CURRENCY',
      columnKey: 'di_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 49,
    },
    {
      defaultIsVisible: true,
      description: 'Batches JCB Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'JCB Refund Count',
      reportColumnId: 99,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 99,
      displayType: 'STRING',
      columnKey: 'jcb_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 66,
    },
    {
      defaultIsVisible: false,
      description: 'Batches MasterCard Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'MasterCard Amount',
      reportColumnId: 100,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 100,
      displayType: 'CURRENCY',
      columnKey: 'mc_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 67,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Merchant Category Code',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Merchant Category Code',
      reportColumnId: 128,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 128,
      displayType: 'STRING',
      columnKey: 'merchant_category_code',
      categoryDescription: 'Chargebacks Case Page Page No Filter (en-US)',
      categoryKey: 'merchantInformation',
      categoryName: 'Page No Filter',
      displayOrder: 95,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Region',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Region',
      reportColumnId: 124,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 124,
      displayType: 'STRING',
      columnKey: 'region',
      categoryDescription: 'Transaction Finder MID Hierarchy',
      categoryKey: 'header',
      categoryName: 'MID Hierarchy',
      displayOrder: 91,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Diners Club Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Diners Club Refund Amount',
      reportColumnId: 80,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 80,
      displayType: 'CURRENCY',
      columnKey: 'dc_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 47,
    },
    {
      defaultIsVisible: true,
      description: 'Batches EBT Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'EBT Batch Count',
      reportColumnId: 89,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 89,
      displayType: 'STRING',
      columnKey: 'ebt_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 56,
    },
    {
      defaultIsVisible: true,
      description: 'Batches MasterCard Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'MasterCard Purchase Count',
      reportColumnId: 103,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 103,
      displayType: 'STRING',
      columnKey: 'mc_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 70,
    },
    {
      defaultIsVisible: true,
      description: 'Batches JCB Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'JCB Batch Count',
      reportColumnId: 95,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 95,
      displayType: 'STRING',
      columnKey: 'jcb_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 62,
    },
    {
      defaultIsVisible: true,
      description: 'Batches China Union Pay Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'China Union Pay Purchase Count',
      reportColumnId: 67,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 67,
      displayType: 'STRING',
      columnKey: 'cup_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 34,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Debit Card Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Debit Card Purchase Amount',
      reportColumnId: 72,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 72,
      displayType: 'CURRENCY',
      columnKey: 'db_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 39,
    },
    {
      defaultIsVisible: false,
      description: 'Batches CBRT Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'CBRT Purchase Amount',
      reportColumnId: 60,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 60,
      displayType: 'CURRENCY',
      columnKey: 'cbrt_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 27,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Associate',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Associate',
      reportColumnId: 126,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 126,
      displayType: 'STRING',
      columnKey: 'associate',
      categoryDescription: 'Transaction Finder MID Hierarchy',
      categoryKey: 'header',
      categoryName: 'MID Hierarchy',
      displayOrder: 93,
    },
    {
      defaultIsVisible: true,
      description: 'Batches File Date',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'File Date',
      reportColumnId: 34,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 34,
      displayType: 'DATE',
      columnKey: 'file_date_full',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 1,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Batch Control Number',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Batch Control Number',
      reportColumnId: 36,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 36,
      displayType: 'STRING',
      columnKey: 'batch_control_number',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 3,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Amex Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Amex Refund Count',
      reportColumnId: 57,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 57,
      displayType: 'STRING',
      columnKey: 'ax_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 24,
    },
    {
      defaultIsVisible: false,
      description: 'Batches JCB Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'JCB Purchase Amount',
      reportColumnId: 96,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 96,
      displayType: 'CURRENCY',
      columnKey: 'jcb_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 63,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Debit Card Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Debit Card Batch Count',
      reportColumnId: 71,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 71,
      displayType: 'STRING',
      columnKey: 'db_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 38,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Visa Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Visa Refund Count',
      reportColumnId: 117,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 117,
      displayType: 'STRING',
      columnKey: 'vi_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 84,
    },
    {
      defaultIsVisible: true,
      description: 'Batches CBRT Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'CBRT Batch Amount',
      reportColumnId: 58,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 58,
      displayType: 'CURRENCY',
      columnKey: 'cbrt_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 25,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Private Label Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Private Label Batch Count',
      reportColumnId: 107,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 107,
      displayType: 'STRING',
      columnKey: 'pl_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 74,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Merchant Name',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Merchant Name',
      reportColumnId: 37,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 37,
      displayType: 'STRING',
      columnKey: 'merchant_dba_name',
      categoryDescription: 'Chargebacks Case Page Page No Filter (en-US)',
      categoryKey: 'merchantInformation',
      categoryName: 'Page No Filter',
      displayOrder: 4,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Adjustment Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Adjusted Refund Amount',
      reportColumnId: 50,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 50,
      displayType: 'CURRENCY',
      columnKey: 'adj_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 17,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Visa Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Visa Purchase Amount',
      reportColumnId: 114,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 114,
      displayType: 'CURRENCY',
      columnKey: 'vi_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 81,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Debit Card Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Debit Card Batch Amount',
      reportColumnId: 70,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 70,
      displayType: 'CURRENCY',
      columnKey: 'db_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 37,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Diners Club Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Diners Club Purchase Amount',
      reportColumnId: 78,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 78,
      displayType: 'CURRENCY',
      columnKey: 'dc_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 45,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Visa Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Visa Amount',
      reportColumnId: 112,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 112,
      displayType: 'CURRENCY',
      columnKey: 'vi_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 79,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Amex Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Amex Amount',
      reportColumnId: 52,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 52,
      displayType: 'CURRENCY',
      columnKey: 'ax_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 19,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Merchant Number',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Merchant Number',
      reportColumnId: 122,
      sortDirection: 'ASCENDING',
      sortOrderPriority: 1,
      templateId: 122,
      displayType: 'STRING',
      columnKey: 'merchant_number',
      categoryDescription: 'Chargebacks Case Page Page No Filter (en-US)',
      categoryKey: 'merchantInformation',
      categoryName: 'Page No Filter',
      displayOrder: 89,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Visa Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Visa Purchase Count',
      reportColumnId: 115,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 115,
      displayType: 'STRING',
      columnKey: 'vi_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 82,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Diners Club Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Diners Club Purchase Count',
      reportColumnId: 79,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 79,
      displayType: 'STRING',
      columnKey: 'dc_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 46,
    },
    {
      defaultIsVisible: false,
      description: 'Batches EBT Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'EBT Batch Amount',
      reportColumnId: 88,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 88,
      displayType: 'CURRENCY',
      columnKey: 'ebt_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 55,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Chain',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Chain',
      reportColumnId: 127,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 127,
      displayType: 'STRING',
      columnKey: 'chain',
      categoryDescription: 'Transaction Finder MID Hierarchy',
      categoryKey: 'header',
      categoryName: 'MID Hierarchy',
      displayOrder: 94,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Card Acceptor ID',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Card Acceptor ID',
      reportColumnId: 35,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 35,
      displayType: 'STRING',
      columnKey: 'card_acceptor_id',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 2,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Debit Card Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Debit Card Refund Count',
      reportColumnId: 75,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 75,
      displayType: 'STRING',
      columnKey: 'db_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 42,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Refund Amount',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Refund Amount',
      reportColumnId: 45,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 45,
      displayType: 'CURRENCY',
      columnKey: 'refund_amount',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 12,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Discover Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Discover Batch Count',
      reportColumnId: 83,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 83,
      displayType: 'STRING',
      columnKey: 'di_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 50,
    },
    {
      defaultIsVisible: false,
      description: 'Batches EBT Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'EBT Refund Amount',
      reportColumnId: 92,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 92,
      displayType: 'CURRENCY',
      columnKey: 'ebt_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 59,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Source File Key',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Source File Key',
      reportColumnId: 129,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 129,
      displayType: 'STRING',
      columnKey: 'source_file_key',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 96,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Visa Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Visa Refund Amount',
      reportColumnId: 116,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 116,
      displayType: 'CURRENCY',
      columnKey: 'vi_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 83,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Adjustment Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Adjusted Refund Count',
      reportColumnId: 51,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 51,
      displayType: 'STRING',
      columnKey: 'adj_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 18,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Return Credit Count',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Return Credit Count',
      reportColumnId: 120,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 120,
      displayType: 'STRING',
      columnKey: 'return_credit_count',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 87,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Diners Club Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Diners Club Batch Count',
      reportColumnId: 77,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 77,
      displayType: 'STRING',
      columnKey: 'dc_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 44,
    },
    {
      defaultIsVisible: true,
      description: 'Batches JCB Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'JCB Batch Amount',
      reportColumnId: 94,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 94,
      displayType: 'CURRENCY',
      columnKey: 'jcb_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 61,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Private Label Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Private Label Batch Amount',
      reportColumnId: 106,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 106,
      displayType: 'CURRENCY',
      columnKey: 'pl_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 73,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Purchase Credit Count',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Purchase Credit Count',
      reportColumnId: 118,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 118,
      displayType: 'STRING',
      columnKey: 'purchase_credit_count',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 85,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Adjustment Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Adjusted Purchase Count',
      reportColumnId: 49,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 49,
      displayType: 'STRING',
      columnKey: 'adj_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 16,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Debit Card Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Debit Card Refund Amount',
      reportColumnId: 74,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 74,
      displayType: 'CURRENCY',
      columnKey: 'db_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 41,
    },
    {
      defaultIsVisible: true,
      description: 'Batches CBRT Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'CBRT Purchase Count',
      reportColumnId: 61,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 61,
      displayType: 'STRING',
      columnKey: 'cbrt_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 28,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Debit Card Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Debit Card Purchase Count',
      reportColumnId: 73,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 73,
      displayType: 'STRING',
      columnKey: 'db_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 40,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Discover Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Discover Purchase Count',
      reportColumnId: 85,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 85,
      displayType: 'STRING',
      columnKey: 'di_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 52,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Total Amount',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Total Amount',
      reportColumnId: 41,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 41,
      displayType: 'CURRENCY',
      columnKey: 'total_tot_amount',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 8,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Amex Purchase Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Amex Purchase Amount',
      reportColumnId: 54,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 54,
      displayType: 'CURRENCY',
      columnKey: 'ax_purchase_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 21,
    },
    {
      defaultIsVisible: true,
      description: 'Batches JCB Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'JCB Refund Amount',
      reportColumnId: 98,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 98,
      displayType: 'CURRENCY',
      columnKey: 'jcb_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 65,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Adjustment Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Adjustment Amount',
      reportColumnId: 46,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 46,
      displayType: 'CURRENCY',
      columnKey: 'adj_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 13,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Amex Purchase Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Amex Purchase Count',
      reportColumnId: 55,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 55,
      displayType: 'STRING',
      columnKey: 'ax_purchase_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 22,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Purchase Credit Amount',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Purchase Credit Amount',
      reportColumnId: 119,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 119,
      displayType: 'CURRENCY',
      columnKey: 'purchase_credit_amount',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 86,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Timezone Offset',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Timezone Offset',
      reportColumnId: 132,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 132,
      displayType: 'STRING',
      columnKey: 'timezone_offset',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 99,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Visa Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Visa Count',
      reportColumnId: 113,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 113,
      displayType: 'STRING',
      columnKey: 'vi_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 80,
    },
    {
      defaultIsVisible: true,
      description: 'Batches CBRT Refund Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'CBRT Refund Count',
      reportColumnId: 63,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 63,
      displayType: 'STRING',
      columnKey: 'cbrt_refund_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 30,
    },
    {
      defaultIsVisible: false,
      description: 'Batches MasterCard Refund Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'MasterCard Refund Amount',
      reportColumnId: 104,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 104,
      displayType: 'CURRENCY',
      columnKey: 'mc_refund_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 71,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Diners Club Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Diners Club Batch Amount',
      reportColumnId: 76,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 76,
      displayType: 'CURRENCY',
      columnKey: 'dc_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 43,
    },
    {
      defaultIsVisible: true,
      description: 'Batches CBRT Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'CBRT Batch Count',
      reportColumnId: 59,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 59,
      displayType: 'STRING',
      columnKey: 'cbrt_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 26,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Purchase Amount',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Purchase Amount',
      reportColumnId: 43,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 43,
      displayType: 'CURRENCY',
      columnKey: 'purchase_amount',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 10,
    },
    {
      defaultIsVisible: false,
      description: 'Batches Total Count',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Total Count',
      reportColumnId: 40,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 40,
      displayType: 'STRING',
      columnKey: 'total_tot_count',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 7,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Purchase Count',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'Purchase Count',
      reportColumnId: 42,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 42,
      displayType: 'STRING',
      columnKey: 'purchase_count',
      categoryDescription: 'Batches ETL Batch ID',
      categoryKey: 'batchInformation',
      categoryName: 'ETL Batch ID',
      displayOrder: 9,
    },
    {
      defaultIsVisible: true,
      description: 'Batches Adjustment Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'Adjustment Count',
      reportColumnId: 47,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 47,
      displayType: 'STRING',
      columnKey: 'adj_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 14,
    },
    {
      defaultIsVisible: false,
      description: 'Batches China Union Pay Batch Amount',
      isRequired: false,
      isSortable: false,
      isSummaryColumn: false,
      name: 'China Union Pay Batch Amount',
      reportColumnId: 64,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 64,
      displayType: 'CURRENCY',
      columnKey: 'cup_amount',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 31,
    },
    {
      defaultIsVisible: true,
      description: 'Batches China Union Pay Batch Count',
      isRequired: false,
      isSortable: true,
      isSummaryColumn: false,
      name: 'China Union Pay Batch Count',
      reportColumnId: 65,
      sortDirection: null,
      sortOrderPriority: 0,
      templateId: 65,
      displayType: 'STRING',
      columnKey: 'cup_count',
      categoryDescription: 'Batches Visa Refund Count',
      categoryKey: 'cardBreakdown',
      categoryName: 'Visa Refund Count',
      displayOrder: 32,
    },
  ];
}

/* eslint-enable */
