export const ADD_TO_GLOBAL_FILTER = 'ADD_TO_GLOBAL_FILTER';
export const REMOVE_FROM_GLOBAL_FILTER = 'REMOVE_FROM_GLOBAL_FILTER';
export const CLEAR_GLOBAL_FILTER = 'CLEAR_GLOBAL_FILTER';

export const REQUEST_ROLES_PERMISSIONS = 'REQUEST_ROLES_PERMISSIONS';
export const RECEIVE_ROLES_PERMISSIONS_SUCCESS = 'RECEIVE_ROLES_PERMISSIONS_SUCCESS';
export const RECEIVE_ROLES_PERMISSIONS_FAILURE = 'RECEIVE_ROLES_PERMISSIONS_FAILURE';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export const REQUEST_AUTH_LOGIN = 'REQUEST_AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS_SUCCESS = 'RECEIVE_USERS_SUCCESS';
export const RECEIVE_USERS_FAILURE = 'RECEIVE_USERS_FAILURE';

export const REQUEST_USER_BY_ID = 'REQUEST_USER_BY_ID';
export const RECEIVE_USER_BY_ID_SUCCESS = 'RECEIVE_USER_BY_ID_SUCCESS';
export const RECEIVE_USER_BY_ID_FAILURE = 'RECEIVE_USER_BY_ID_FAILURE';

export const REQUEST_ALL_USERS_BY_MERCHANT_ID = 'REQUEST_ALL_USERS_BY_MERCHANT_ID';
export const RECEIVE_ALL_USERS_BY_MERCHANT_ID_SUCCESS = 'RECEIVE_ALL_USERS_BY_MERCHANT_ID_SUCCESS';
export const RECEIVE_ALL_USERS_BY_MERCHANT_ID_FAILURE = 'RECEIVE_ALL_USERS_BY_MERCHANT_ID_FAILURE';

export const REQUEST_SAVE_USER = 'REQUEST_SAVE_USER';
export const RECEIVE_SAVE_USER_SUCCESS = 'RECEIVE_SAVE_USER_SUCCESS';
export const RECEIVE_SAVE_USER_FAILURE = 'RECEIVE_SAVE_USER_FAILURE';

export const REQUEST_USER_DATA_ACCESS = 'REQUEST_USER_DATA_ACCESS';
export const RECEIVE_USER_DATA_ACCESS_SUCCESS = 'RECEIVE_USER_DATA_ACCESS_SUCCESS';
export const RECEIVE_USER_DATA_ACCESS_FAILURE = 'RECEIVE_USER_DATA_ACCESS_FAILURE';

export const REQUEST_UPDATE_LOCATION = 'REQUEST_UPDATE_LOCATION';
export const RECEIVE_UPDATE_LOCATION_SUCCESS = 'RECEIVE_UPDATE_LOCATION_SUCCESS';
export const RECEIVE_UPDATE_LOCATION_FAILURE = 'RECEIVE_UPDATE_LOCATION_FAILURE';

export const REQUEST_USER_MERCHANTS = 'REQUEST_USER_MERCHANTS';
export const RECEIVE_USER_MERCHANTS_SUCCESS = 'RECEIVE_USER_MERCHANTS_SUCCESS';
export const RECEIVE_USER_MERCHANTS_FAILURE = 'RECEIVE_USER_MERCHANTS_FAILURE';
export const CLEAR_LAST_REGISTERED_MERCHANT = 'CLEAR_LAST_REGISTERED_MERCHANT';

export const REQUEST_MERCHANTS = 'REQUEST_MERCHANTS';
export const RECEIVE_MERCHANTS_SUCCESS = 'RECEIVE_MERCHANTS_SUCCESS';
export const RECEIVE_MERCHANTS_FAILURE = 'RECEIVE_MERCHANTS_FAILURE';

export const POST_REGISTER_MERCHANT = 'POST_REGISTER_MERCHANT';
export const REGISTER_MERCHANT_SUCCESS = 'REGISTER_MERCHANT_SUCCESS';
export const REGISTER_MERCHANT_FAILURE = 'REGISTER_MERCHANT_FAILURE';

export const REQUEST_USER_SUBSCRIPTIONS = 'REQUEST_USER_SUBSCRIPTIONS';
export const RECEIVE_USER_SUBSCRIPTIONS_SUCCESS = 'RECEIVE_USER_SUBSCRIPTIONS_SUCCESS';
export const RECEIVE_USER_SUBSCRIPTIONS_FAILURE = 'RECEIVE_USER_SUBSCRIPTIONS_FAILURE';

export const REQUEST_USER_PREFERENCES = 'REQUEST_USER_PREFERENCES';
export const RECEIVE_USER_PREFERENCES_SUCCESS = 'RECEIVE_USER_PREFERENCES_SUCCESS';
export const RECEIVE_USER_PREFERENCES_FAILURE = 'RECEIVE_USER_PREFERENCES_FAILURE';

export const REQUEST_SAVE_USER_PREFERENCES = 'REQUEST_SAVE_USER_PREFERENCES';
export const RECEIVE_SAVE_USER_PREFERENCES_SUCCESS = 'RECEIVE_SAVE_USER_PREFERENCES_SUCCESS';
export const RECEIVE_SAVE_USER_PREFERENCES_FAILURE = 'RECEIVE_SAVE_USER_PREFERENCES_FAILURE';

export const REQUEST_SAVE_USER_SUBSCRIPTIONS = 'REQUEST_SAVE_USER_SUBSCRIPTIONS';
export const RECEIVE_SAVE_USER_SUBSCRIPTIONS_SUCCESS = 'RECEIVE_SAVE_USER_SUBSCRIPTIONS_SUCCESS';
export const RECEIVE_SAVE_USER_SUBSCRIPTIONS_FAILURE = 'RECEIVE_SAVE_USER_SUBSCRIPTIONS_FAILURE';

export const REQUEST_REPORTS = 'REQUEST_REPORTS';
export const RECEIVE_REPORTS_SUCCESS = 'RECEIVE_REPORTS_SUCCESS';
export const RECEIVE_REPORTS_FAILURE = 'RECEIVE_REPORTS_FAILURE';

export const REQUEST_REPORT_METADATA = 'REQUEST_REPORT_METADATA';
export const RECEIVE_REPORT_METADATA_SUCCESS = 'RECEIVE_REPORT_METADATA_SUCCESS';
export const RECEIVE_REPORT_METADATA_FAILURE = 'RECEIVE_REPORT_METADATA_FAILURE';

export const REQUEST_REPORT_DATA = 'REQUEST_REPORT_DATA';
export const RECEIVE_REPORT_DATA_SUCCESS = 'RECEIVE_REPORT_DATA_SUCCESS';
export const RECEIVE_REPORT_DATA_FAILURE = 'RECEIVE_REPORT_DATA_FAILURE';

export const REQUEST_REPORT_VISUALIZATIONS = 'REQUEST_REPORT_VISUALIZATIONS';
export const RECEIVE_REPORT_VISUALIZATIONS_SUCCESS = 'RECEIVE_REPORT_VISUALIZATIONS_SUCCESS';
export const RECEIVE_REPORT_VISUALIZATIONS_FAILURE = 'RECEIVE_REPORT_VISUALIZATIONS_FAILURE';

export const SET_CURRENT_REPORT_FILTER = 'SET_CURRENT_REPORT_FILTER';
export const CLEAR_CURRENT_REPORT_FILTER = 'CLEAR_CURRENT_REPORT_FILTER';

export const REQUEST_REPORT_USER_FILTERS = 'REQUEST_REPORT_USER_FILTERS';
export const RECEIVE_REPORT_USER_FILTERS_SUCCESS = 'RECEIVE_REPORT_USER_FILTERS_SUCCESS';
export const RECEIVE_REPORT_USER_FILTERS_FAILURE = 'RECEIVE_REPORT_USER_FILTERS_FAILURE';

export const REQUEST_SAVE_REPORT_FILTER = 'REQUEST_SAVE_REPORT_FILTER';
export const RECEIVE_SAVE_REPORT_FILTER_SUCCESS = 'RECEIVE_SAVE_REPORT_FILTER_SUCCESS';
export const RECEIVE_SAVE_REPORT_FILTER_FAILURE = 'RECEIVE_SAVE_REPORT_FILTER_FAILURE';

export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES_SUCCESS = 'RECEIVE_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGES_FAILURE = 'RECEIVE_MESSAGES_FAILURE';

export const REQUEST_MESSAGE_COUNT = 'REQUEST_MESSAGE_COUNT';
export const RECEIVE_MESSAGE_COUNT_SUCCESS = 'RECEIVE_MESSAGE_COUNT_SUCCESS';
export const RECEIVE_MESSAGE_COUNT_FAILURE = 'RECEIVE_MESSAGE_COUNT_FAILURE';

export const REQUEST_MESSAGES_UPDATE_STATUS = 'REQUEST_MESSAGES_UPDATE_STATUS';
export const RECEIVE_MESSAGES_UPDATE_STATUS_SUCCESS = 'RECEIVE_MESSAGES_UPDATE_STATUS_SUCCESS';
export const RECEIVE_MESSAGES_UPDATE_STATUS_FAILURE = 'RECEIVE_MESSAGES_UPDATE_STATUS_FAILURE';

export const RECEIVE_MESSAGES_UPDATE_SUCCESS = 'RECEIVE_MESSAGES_UPDATE_SUCCESS';

export const REQUEST_REPORT_ROW_DETAILS = 'REQUEST_REPORT_ROW_DETAILS';
export const RECEIVE_REPORT_ROW_DETAILS_SUCCESS = 'RECEIVE_REPORT_ROW_DETAILS_SUCCESS';
export const RECEIVE_REPORT_ROW_DETAILS_FAILURE = 'RECEIVE_REPORT_ROW_DETAILS_FAILURE';

export const REQUEST_STATEMENTS = 'REQUEST_STATEMENTS';
export const RECEIVE_STATEMENTS_SUCCESS = 'RECEIVE_STATEMENTS_SUCCESS';
export const RECEIVE_STATEMENTS_FAILURE = 'RECEIVE_STATEMENTS_FAILURE';

export const REQUEST_NEW_AUTH_PREFERENCES = 'REQUEST_NEW_AUTH_PREFERENCES';
export const RECEIVE_NEW_AUTH_PREFERENCES_SUCCESS = 'RECEIVE_NEW_AUTH_PREFERENCES_SUCCESS';
export const RECEIVE_NEW_AUTH_PREFERENCES_FAILURE = 'RECEIVE_NEW_AUTH_PREFERENCES_FAILURE';

// reports API v2 actions
export const REQUEST_SAVE_REPORT_V2 = 'REQUEST_SAVE_REPORT_V2';
export const RECEIVE_SAVE_REPORT_SUCCESS_V2 = 'RECEIVE_SAVE_REPORT_SUCCESS_V2';
export const RECEIVE_SAVE_REPORT_FAILURE_V2 = 'RECEIVE_SAVE_REPORT_FAILURE_V2';

export const REQUEST_REPORTS_V2 = 'REQUEST_REPORTS_V2';
export const RECEIVE_REPORTS_SUCCESS_V2 = 'RECEIVE_REPORTS_SUCCESS_V2';
export const RECEIVE_REPORTS_FAILURE_V2 = 'RECEIVE_REPORTS_FAILURE_V2';

export const REQUEST_ONE_REPORT_V2 = 'REQUEST_ONE_REPORT_V2';
export const RECEIVE_ONE_REPORT_SUCCESS_V2 = 'RECEIVE_ONE_REPORT_SUCCESS_V2';
export const RECEIVE_ONE_REPORT_FAILURE_V2 = 'RECEIVE_ONE_REPORT_FAILURE_V2';

export const REQUEST_REPORT_DATA_V2 = 'REQUEST_REPORT_DATA_V2';
export const RECEIVE_REPORT_DATA_SUCCESS_V2 = 'RECEIVE_REPORT_DATA_SUCCESS_V2';
export const RECEIVE_REPORT_DATA_FAILURE_V2 = 'RECEIVE_REPORT_DATA_FAILURE_V2';

export const REQUEST_REPORT_SUMMARY_V2 = 'REQUEST_REPORT_SUMMARY_V2';
export const RECEIVE_REPORT_SUMMARY_SUCCESS_V2 = 'RECEIVE_REPORT_SUMMARY_SUCCESS_V2';
export const RECEIVE_REPORT_SUMMARY_FAILURE_V2 = 'RECEIVE_REPORT_SUMMARY_FAILURE_V2';

export const REQUEST_REPORT_VISUALIZATIONS_V2 = 'REQUEST_REPORT_VISUALIZATIONS_V2';
export const RECEIVE_REPORT_VISUALIZATIONS_SUCCESS_V2 = 'RECEIVE_REPORT_VISUALIZATIONS_SUCCESS_V2';
export const RECEIVE_REPORT_VISUALIZATIONS_FAILURE_V2 = 'RECEIVE_REPORT_VISUALIZATIONS_FAILURE_V2';

export const REQUEST_REPORT_USER_FILTERS_V2 = 'REQUEST_REPORT_USER_FILTERS_V2';
export const RECEIVE_REPORT_USER_FILTERS_SUCCESS_V2 = 'RECEIVE_REPORT_USER_FILTERS_SUCCESS_V2';
export const RECEIVE_REPORT_USER_FILTERS_FAILURE_V2 = 'RECEIVE_REPORT_USER_FILTERS_FAILURE_V2';

export const REQUEST_DELETE_REPORT_USER_FILTERS_V2 = 'REQUEST_DELETE_REPORT_USER_FILTERS_V2';
export const RECEIVE_DELETE_REPORT_USER_FILTERS_SUCCESS_V2 = 'RECEIVE_DELETE_REPORT_USER_FILTERS_SUCCESS_V2';
export const RECEIVE_DELETE_REPORT_USER_FILTERS_FAILURE_V2 = 'RECEIVE_DELETE_REPORT_USER_FILTERS_FAILURE_V2';

export const REQUEST_SAVE_REPORT_FILTER_V2 = 'REQUEST_SAVE_REPORT_FILTER_V2';
export const RECEIVE_SAVE_REPORT_FILTER_SUCCESS_V2 = 'RECEIVE_SAVE_REPORT_FILTER_SUCCESS_V2';
export const RECEIVE_SAVE_REPORT_FILTER_FAILURE_V2 = 'RECEIVE_SAVE_REPORT_FILTER_FAILURE_V2';

export const REQUEST_TEMPLATES = 'REQUEST_TEMPLATES';
export const RECEIVE_TEMPLATES_SUCCESS = 'RECEIVE_TEMPLATES_SUCCESS';
export const RECEIVE_TEMPLATES_FAILURE = 'RECEIVE_TEMPLATES_FAILURE';
export const REQUEST_ONE_TEMPLATE = 'REQUEST_ONE_TEMPLATE';
export const RECEIVE_ONE_TEMPLATE_SUCCESS = 'RECEIVE_ONE_TEMPLATE_SUCCESS';
export const RECEIVE_ONE_TEMPLATE_FAILURE = 'RECEIVE_ONE_TEMPLATE_FAILURE';

export const SET_FEATURE_FLAGS = 'SET_FEATURE_FLAGS';
export const CLEAR_REPORT_DATA = 'CLEAR_REPORT_DATA';
